#!/bin/bash

ps aux | grep "dplan_btl" | grep -v grep | awk '{print $2}' | xargs -I^ kill -9 -^

case "$1" in
    "c" | "C" | "clean" | "Clean" ) rm -rf log/* ; rm -rf core.* core ;;
    * ) ;;
esac

./bin/dplan_btl ../etc/bench.conf

