#!/bin/bash

ps aux | grep "dplan_ol" | grep -v grep | awk '{print $2}' | xargs -I^ kill -9 -^

case "$1" in
    "c" | "C" | "clean" | "Clean" ) rm -rf log/* ; rm -rf core.* core ;;
    * ) ;;
esac

./bin/dplan_ol ../etc/bench.conf

