SET(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})
FIND_LIBRARY( UNWIND_LIBRARY
	NAMES unwind
	PATHS /usr/local/lib
	DOC "The unwind library")

IF (UNWIND_LIBRARY)
	SET( UNWIND_FOUND 1 CACHE STRING "Set to 1 if unwind is found, 0 otherwise")
ELSE (UNWIND_LIBRARY)
	SET( UNWIND_FOUND 0 CACHE STRING "Set to 1 if unwind is found, 0 otherwise")
ENDIF (UNWIND_LIBRARY)

MARK_AS_ADVANCED( UNWIND_FOUND )

IF (UNWIND_FOUND)
	MESSAGE(STATUS "找到了 unwind 库")
ELSE (UNWIND_FOUND)
	MESSAGE(FATAL_ERROR "没有找到 unwind 库 :请安装它, 建议源码安装")
ENDIF (UNWIND_FOUND)


